version: 2

shared:
  build: &build
    steps:
      - checkout
      - run: curl -fSL -o rebar3 "https://s3.amazonaws.com/rebar3/rebar3"
      - run: chmod +x ./rebar3
      - run: ./rebar3 local install
      - run: rm ./rebar3

jobs:
  erlang-21:
    <<: *build
    docker:
      - image: erlang:21
  erlang-20:
    <<: *build
    docker:
      - image: erlang:20

workflows:
  version: 2
  build_and_test:
    jobs:
      - erlang-21
      - erlang-20
