version: 2.1
orbs:
  grisp: grisp/grisp@0.0.2
jobs:
    build:
        docker:
          - image: 'opensuse:leap'
        steps:
          - grisp/install-erlang
          - grisp/install-rebar3
          - grisp/install-toolchain
          - grisp/create-grisp-project:
              build-otp: true
              deploy-destination: '/tmp/deploy'
              grisp-repo: "${CIRCLE_REPOSITORY_URL}"
              grisp-revision: "${CIRCLE_SHA1}"
          - run:
              command: source ~/.bashrc && rebar3 grisp build --tar true
              working_directory: /root/ciproject
          - run:
              command: source ~/.bashrc && rebar3 grisp deploy -v 0.1.0 -n ciproject
              working_directory: /root/ciproject
          - persist_to_workspace:
              root: /root/ciproject/_grisp/
              paths:
                - "otp/*/package/*.tar.gz"
    deploy:
      docker:
        - image: 'opensuse:leap'
      steps:
        - run: 'zypper install -y aws-cli tar gzip'
        - attach_workspace:
            at: /root/
        - deploy:
            command: "ARCHIVENAME=$(basename otp/*/package/grisp_otp_build_*.tar.gz) &&
            COUNT=$(aws s3 ls s3://grisp/platforms/grisp_base/otp/$ARCHIVENAME | wc -l) &&
            if [ $COUNT -eq 0 ]; then
            aws s3 cp otp/*/package/grisp_otp_build_*.tar.gz s3://grisp/platforms/grisp_base/otp/ --acl public-read;
            else
            echo File already on S3;
            fi 2>&1 > /tmp/deploy_log"
            working_directory: /root
        - store_artifacts:
            path: /tmp/deploy_log
            destination: deploy_log
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
