version: 2

shared:
  build: &build
    steps:
      - checkout
      - run:
          name: Download Rebar 3
          command: curl -fSL -o rebar3 "https://s3.amazonaws.com/rebar3/rebar3"
      - run:
          name: Install Rebar 3 locally
          command: chmod +x ./rebar3 && ./rebar3 local install && rm ./rebar3
      - run:
          name: Update PATH and Define Environment Variable at Runtime
          command: |
            echo 'export PATH=$HOME/.cache/rebar3/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
      - run: rebar3 version

jobs:
  erlang-21:
    <<: *build
    docker:
      - image: erlang:21
  erlang-20:
    <<: *build
    docker:
      - image: erlang:20

workflows:
  version: 2
  build_and_test:
    jobs:
      - erlang-21
      - erlang-20
