version: 2.1
orbs:
  grisp: grisp-test/grisp@dev:var-fix
jobs:
    build:
        docker:
          - image: 'opensuse:leap'
        steps:
          - grisp/install-erlang
          - grisp/install-rebar3
          - grisp/install-toolchain
          - grisp/create-grisp-project:
              deploy-destination: '/tmp/deploy'
          - run:
              command: source ~/.bashrc && rebar3 grisp build --tar true
              working_directory: /root/ciproject
          - run:
              command: source ~/.bashrc && rebar3 grisp deploy -v 0.1.0 -n ciproject
              working_directory: /root/ciproject
          # TODO: deploy OTP to aws
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
