version: 2
jobs:
  build:
    docker:
      - image: erlang:21
    steps:
      - checkout
      - run: echo "Build"
  test:
    docker:
      - image: erlang:21
    steps:
      - checkout
      - run: echo "Test"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
